from setuptools import find_packages, setup

setup(
    name="cure-ground",
    version="0.1.0",
    packages=find_packages(),
    install_requires=[
        "numpy>=1.23.0",
        "psutil>=5.9.0",
        "PyOpenGL>=3.1.7",
        "pyqt6",
        "typer>=0.9.0",
        "rich>=13.0.0",
        "pyserial>=3.5",
        "pandas>=2.0.0",
        "matplotlib>=3.7.0",
        "tqdm>=4.65.0",
        "kaleido>=0.2.1",
        "questionary",
        "plotly",
        "pyyaml",
        "pyqtgraph",
        "pre-commit",
        "ruff",
    ],
    entry_points={
        "console_scripts": [
            "cure-ground=cure_ground.cli.main:main",
        ],
    },
    author="Clemson University Rocket Engineering",
    author_email="",
    description="CURE Ground Station Software",
    long_description=open("README.md", encoding="utf-8").read(),
    long_description_content_type="text/markdown",
    url="https://github.com/CURocketEngineering/Ground-Station",
    classifiers=[
        "Development Status :: 3 - Alpha",
        "Intended Audience :: Science/Research",
        "License :: OSI Approved :: MIT License",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
        "Programming Language :: Python :: 3.12",
        "Programming Language :: Python :: 3.13",
        "Programming Language :: Python :: 3.14",
    ],
    python_requires=">=3.9",
)
