import enum

"""
States.h

#ifndef FLIGHT_STATES_H
#define FLIGHT_STATES_H

enum FlightState {
    STATE_UNARMED,
    STATE_ARMED,
    STATE_ASCENT,
    STATE_POWERED_ASCENT,
    STATE_COAST_ASCENT,
    STATE_DESCENT,
    STATE_DROGUE_DEPLOYED,
    STATE_MAIN_DEPLOYED,
    STATE_LANDED
};

#endif

"""


class States(enum.Enum):
    STATE_UNARMED = 0
    STATE_ARMED = 1
    STATE_ASCENT = 2
    STATE_POWERED_ASCENT = 3
    STATE_COAST_ASCENT = 4
    STATE_DESCENT = 5
    STATE_DROGUE_DEPLOYED = 6
    STATE_MAIN_DEPLOYED = 7
    STATE_LANDED = 8
